# i3 doesn't have "normalizations" feature that why we disable them here.
# Enable back splits if this is enabled
# enable-normalization-flatten-containers = false
# enable-normalization-opposite-orientation-for-nested-containers = false

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
start-at-login = true

accordion-padding = 5

[mode.main.binding]
# https://gist.github.com/stecman/97bbe21b59613aa6c6c025ae85871438
alt-enter = '''exec-and-forget osascript -e '
tell application "System Events" to tell process "kitty"
  click menu item "New OS Window" of menu 1 of menu bar item "Shell" of menu bar 1
end tell''''

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
# alt-x = 'split horizontal'
# alt-v = 'split vertical'

alt-h = 'focus left --boundaries-action wrap-around-the-workspace'
alt-j = 'focus down --boundaries-action wrap-around-the-workspace'
alt-k = 'focus up --boundaries-action wrap-around-the-workspace'
alt-l = 'focus right --boundaries-action wrap-around-the-workspace'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-f = 'fullscreen'

alt-s = 'layout v_accordion'
alt-w = 'layout h_accordion'
alt-e = 'layout tiles vertical horizontal'
alt-shift-space = 'layout floating tiling' # 'floating toggle'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-shift-c = 'reload-config'
alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[workspace-to-monitor-force-assignment]
1 = 'secondary'
2 = 'secondary'
3 = 'main'
4 = 'main'
5 = 'secondary'
6 = 'secondary'
7 = 'secondary'

# osascript -e 'id of app "Application Name"'
[[on-window-detected]]
if.app-id = 'com.microsoft.edgemac'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij.ce'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'org.jkiss.dbeaver.core.product'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.postmanlabs.mac'
run = 'move-node-to-workspace 5'
