vim.cmd.highlight('clear')
if vim.g.syntax_on then
  vim.cmd.syntax('reset')
end
vim.g.colors_name = 'enfocado'

local c = {
  bg_0 = '#181818',
  bg_1 = '#252525',
  bg_2 = '#3b3b3b',
  dim_0 = '#777777',
  fg_0 = '#b9b9b9',
  fg_1 = '#dedede',

  red = '#ed4a46',
  green = '#70b433',
  yellow = '#dbb32d',
  blue = '#368aeb',
  magenta = '#eb6eb7',
  cyan = '#3fc5b7',
  orange = '#e67f43',
  violet = '#a580e2',

  br_red = '#ff5e56',
  br_green = '#83c746',
  br_yellow = '#efc541',
  br_blue = '#4f9cfe',
  br_magenta = '#ff81ca',
  br_cyan = '#56d8c9',
  br_orange = '#fa9153',
  br_violet = '#b891f5',

  base = '#000000',

  blend_error = '#462624',
  blend_hint = '#233246',
  blend_info = '#433a20',
  blend_warn = '#453024',
  blend_ok = '#2d3b23',
  blend_added = '#2c3326',
  blend_modified = '#2c281b',
  blend_removed = '#2e1e1d',
  blend_search = '#62552e',
}

-- nature style
c.accent_0 = c.green
c.accent_1 = c.blue
c.br_accent_0 = c.br_green
c.br_accent_1 = c.br_blue
c.builtin_0 = c.magenta
c.builtin_1 = c.violet
c.br_builtin_0 = c.br_magenta
c.br_builtin_1 = c.br_violet

local hl = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

local groups = {
  -- General interface
  IncSearch = { bg = c.blend_search },
  Search = { fg = '#ffaf00', bg = '#1c1c1c' },
  CurSearch = { bg = c.br_yellow, fg = c.bg_1 },
  LineNr = { fg = c.bg_2 },
  LineNrAbove = { fg = '#949494', bg = '#1c1c1c' },
  LineNrBelow = { fg = '#949494', bg = '#1c1c1c' },
  Accent = { fg = c.br_accent_0 },
  Builtin = { fg = c.br_builtin_0 },
  ColorColumn = { bg = '#303030' },
  Conceal = { fg = c.bg_2 },
  Cursor = { bg = c.fg_0, fg = c.bg_1 },
  lCursor = { bg = c.fg_0, fg = c.bg_1 },
  CursorColumn = { bg = c.bg_1 },
  CursorLine = { bg = '#1c1c1c' },
  CursorLineNr = { fg = '#b891f5', bg = '#1c1c1c', bold = true },
  CursorLineSign = {},
  CursorLineFold = { link = 'CursorLine' },
  DiffAdd = { fg = c.green },
  DiffChange = { fg = c.yellow },
  DiffDelete = { fg = c.red },
  DiffText = { bg = c.bg_2, fg = c.yellow },
  Dimmed = { fg = c.dim_0 },
  Directory = { fg = c.br_blue, bold = true },
  EndOfBuffer = { link = 'NonText' },
  ErrorMsg = { fg = c.br_red },
  FloatBorder = { fg = '#87af5f', bg = '#1c1c1c' },
  FloatTitle = { link = 'NormalFloat' },
  Folded = { fg = c.dim_0 },
  FoldColumn = { fg = c.bg_2 },
  Ignore = { fg = c.bg_2 },
  Match = { fg = c.br_accent_0, bold = true },
  MatchFuzzy = { fg = c.accent_0 },
  MatchParen = { bg = c.bg_2 },
  ModeMsg = { fg = c.fg_0 },
  MoreMsg = { fg = c.br_yellow },
  MsgArea = { link = 'Text' },
  MsgSeparator = { link = 'StatusLineNC' },
  NonText = { fg = '#767676' },
  Normal = { fg = '#bcbcbc', bg = '#1c1c1c' },
  NormalFloat = { fg = '#bcbcbc', bg = '#1c1c1c' },
  NormalNC = { link = 'Normal' },
  Pmenu = { bg = c.bg_1, fg = c.fg_0 },
  PmenuSbar = { bg = c.bg_1 },
  PmenuSel = { bg = c.bg_2 },
  PmenuThumb = { bg = c.bg_2 },
  Question = { fg = c.br_yellow },
  QuickFixLine = { bg = c.bg_1, fg = c.br_accent_0 },
  SignColumn = {},
  SpecialKey = { fg = c.bg_2 },
  SpellBad = { undercurl = true, sp = c.red },
  SpellCap = { undercurl = true, sp = c.blue },
  SpellLocal = { undercurl = true, sp = c.cyan },
  SpellRare = { undercurl = true, sp = c.magenta },
  StatusLine = { bg = '#1c1c1c', fg = '#afffd7' },
  StatusLineNC = { bg = '#1c1c1c', fg = c.bg_2 },
  Substitute = { link = 'Search' },
  TabLine = { bg = c.bg_1, fg = c.bg_2 },
  TabLineFill = { bg = c.bg_1, fg = c.bg_2 },
  TabLineSel = { fg = c.dim_0 },
  TermCursor = { bg = c.fg_0, fg = c.bg_1 },
  Text = { fg = c.fg_0 },
  Title = { fg = c.fg_1, bold = true },
  VertSplit = { fg = c.base },
  WinSeparator = { link = 'VertSplit' },
  Visual = { bg = c.bg_2 },
  VisualNC = { bg = c.bg_1 },
  VisualNOS = { bg = c.bg_2 },
  WarningMsg = { fg = c.br_orange },
  WildMenu = { bg = c.bg_2, fg = c.br_accent_0, bold = true },
  Whitespace = { link = 'NonText' },
  WinBar = { bg = '#1c1c1c', fg = '#afffd7' },
  WinBarNC = { bg = '#1c1c1c', fg = c.dim_0 },

  -- General LSP
  LspInlayHint = { bg = c.bg_1, fg = c.dim_0 },
  LspCodeLens = { link = 'Dimmed' },
  LspReferenceRead = { link = 'Visual' },
  LspReferenceText = { link = 'Visual' },
  LspReferenceWrite = { link = 'Visual' },
  LspSignatureActiveParameter = { link = 'Accent' },

  -- Diagnostics
  DiagnosticDeprecated = { strikethrough = true, sp = c.br_red },
  DiagnosticUnnecessary = { fg = c.bg_2 },
  DiagnosticError = { fg = '#db4b4b', bg = '#1c1c1c' },
  DiagnosticHint = { fg = c.br_blue, bold = true },
  DiagnosticInfo = { fg = c.br_yellow, bold = true },
  DiagnosticWarn = { fg = c.br_orange, bold = true },
  DiagnosticOk = { fg = c.br_green, bold = true },
  DiagnosticFloatingError = { fg = '#db4b4b', bg = '#1c1c1c', bold = true },
  DiagnosticFloatingHint = { fg = '#10b981', bg = '#1c1c1c', bold = true },
  DiagnosticFloatingInfo = { fg = '#0db9d7', bg = '#1c1c1c', bold = true },
  DiagnosticFloatingWarn = { fg = '#ffff00', bg = '#1c1c1c', bold = true },
  DiagnosticFloatingOk = { bg = c.bg_1, fg = c.br_green, bold = true },
  DiagnosticUnderlineError = { undercurl = true, sp = c.br_red },
  DiagnosticUnderlineHint = { undercurl = true, sp = c.br_blue },
  DiagnosticUnderlineInfo = { undercurl = true, sp = c.br_yellow },
  DiagnosticUnderlineWarn = { undercurl = true, sp = c.br_orange },
  DiagnosticUnderlineOk = { undercurl = true, sp = c.br_green },
  DiagnosticVirtualTextError = { bg = c.blend_error, fg = c.br_red, bold = true },
  DiagnosticVirtualTextHint = { bg = c.blend_hint, fg = c.br_blue, bold = true },
  DiagnosticVirtualTextInfo = { bg = c.blend_info, fg = c.br_yellow, bold = true },
  DiagnosticVirtualTextWarn = { bg = c.blend_warn, fg = c.br_orange, bold = true },
  DiagnosticVirtualTextOk = { bg = c.blend_ok, fg = c.br_green, bold = true },
  DiagnosticSignError = { link = 'DiagnosticError' },
  DiagnosticSignHint = { fg = '#10b981', bg = '#1c1c1c' },
  DiagnosticSignInfo = { fg = '#0db9d7', bg = '#1c1c1c' },
  DiagnosticSignWarn = { fg = '#ffff00', bg = '#1c1c1c' },
  DiagnosticSignOk = { link = 'DiagnosticOk' },

  -- General syntax
  Comment = { fg = c.dim_0, italic = true },
  ConstIdentifier = { fg = c.yellow },
  Error = { fg = c.br_red },
  Exception = { fg = c.orange },
  Function = { fg = c.br_accent_0, italic = true },
  FunctionBuiltin = { fg = c.br_builtin_0, italic = true },
  Identifier = { fg = c.accent_0 },
  IdentifierBuiltin = { fg = c.builtin_0 },
  Link = { fg = c.br_cyan, sp = c.br_cyan, underline = true },
  PreProc = { fg = c.accent_1 },
  Special = { fg = c.br_builtin_1 },
  Statement = { fg = c.accent_1 },
  StatementBuiltin = { fg = c.builtin_1 },
  String = { fg = c.cyan },
  Todo = { bg = c.br_cyan, fg = c.bg_1, bold = true },
  Type = { fg = c.br_accent_1, bold = true },
  TypeBuiltin = { fg = c.br_builtin_1, bold = true },
  Boolean = { link = 'StatementBuiltin' },
  Character = { link = 'String' },
  Conditional = { link = 'Statement' },
  Constant = { link = 'Text' },
  Debug = { link = 'Dimmed' },
  Define = { link = 'PreProc' },
  Delimiter = { link = 'Text' },
  Number = { link = 'Constant' },
  Float = { link = 'Number' },
  Include = { link = 'PreProc' },
  Keyword = { link = 'Statement' },
  Label = { link = 'Statement' },
  Macro = { link = 'Define' },
  Method = { link = 'Function' },
  Operator = { link = 'Statement' },
  PreCondit = { link = 'PreProc' },
  Property = { link = 'Type' },
  Repeat = { link = 'Statement' },
  SpecialChar = { link = 'StatementBuiltin' },
  SpecialComment = { link = 'StatementBuiltin' },
  StorageClass = { link = 'Type' },
  Structure = { link = 'Type' },
  Tag = { link = 'Statement' },
  Typedef = { link = 'Type' },
  Bold = { bold = true },
  Italic = { italic = true },
  Underlined = { underline = true },

  -- Treesitter
  ['@text.danger'] = { bg = c.br_red, fg = c.bg_1, bold = true },
  ['@text.note'] = { bg = c.br_yellow, fg = c.bg_1, bold = true },
  ['@text.warning'] = { bg = c.br_orange, fg = c.bg_1, bold = true },
  ['@text.title'] = { fg = c.fg_1 },
  ['@text.literal'] = { fg = c.fg_0, italic = true },
  ['@text'] = { link = 'Text' },
  ['@text.reference'] = { link = '@text.literal' },
  ['@text.uri'] = { link = 'Link' },
  ['@text.todo'] = { link = 'Todo' },
  ['@text.emphasis'] = { italic = true },
  ['@text.strike'] = { strikethrough = true },
  ['@text.strong'] = { bold = true },
  ['@text.underline'] = { underline = true },

  ['@comment'] = { link = 'Comment' },
  ['@annotation'] = { link = 'SpecialComment' },
  ['@attribute'] = { link = 'SpecialComment' },
  ['@punctuation'] = { link = 'Delimiter' },
  ['@punctuation.bracket'] = { link = 'Delimiter' },
  ['@punctuation.delimiter'] = { link = 'Delimiter' },
  ['@punctuation.special'] = { link = 'StatementBuiltin' },

  ['@constant'] = { link = 'ConstIdentifier' },
  ['@constant.builtin'] = { link = 'ConstIdentifier' },
  ['@constant.macro'] = { link = 'ConstIdentifier' },
  ['@define'] = { link = 'PreProc' },
  ['@macro'] = { link = 'Macro' },
  ['@string'] = { link = 'String' },
  ['@string.escape'] = { link = 'StatementBuiltin' },
  ['@string.special'] = { link = 'StatementBuiltin' },
  ['@string.regex'] = { link = 'StatementBuiltin' },
  ['@character'] = { link = 'Character' },
  ['@character.special'] = { link = 'SpecialChar' },
  ['@number'] = { link = 'Number' },
  ['@boolean'] = { link = 'Boolean' },
  ['@float'] = { link = 'Float' },

  ['@function'] = { link = 'Function' },
  ['@function.builtin'] = { link = 'FunctionBuiltin' },
  ['@function.macro'] = { link = 'Function' },
  ['@function.call'] = { link = 'Function' },
  ['@parameter'] = { link = 'Identifier' },
  ['@method'] = { link = 'Method' },
  ['@method.call'] = { link = 'Method' },
  ['@field'] = { link = 'Property' },
  ['@property'] = { link = 'Property' },
  ['@constructor'] = { link = 'Type' },

  ['@conditional'] = { link = 'Conditional' },
  ['@repeat'] = { link = 'Repeat' },
  ['@label'] = { link = 'Label' },
  ['@operator'] = { link = 'Operator' },
  ['@keyword'] = { link = 'Keyword' },
  ['@keyword.function'] = { link = 'Type' },
  ['@keyword.operator'] = { link = 'Operator' },
  ['@keyword.return'] = { link = 'Keyword' },
  ['@exception'] = { link = 'Exception' },
  ['@error'] = { link = 'Error' },

  ['@variable'] = { link = 'Identifier' },
  ['@variable.builtin'] = { link = 'IdentifierBuiltin' },
  ['@symbol'] = { link = 'Identifier' },
  ['@type'] = { link = 'Type' },
  ['@type.definition'] = { link = 'PreProc' },
  ['@type.builtin'] = { link = 'TypeBuiltin' },
  ['@type.qualifier'] = { link = 'Type' },
  ['@namespace'] = { link = 'Text' },
  ['@include'] = { link = 'Include' },
  ['@preproc'] = { link = 'PreProc' },
  ['@debug'] = { link = 'Debug' },
  ['@tag'] = { link = 'Tag' },
  ['@tag.attribute'] = { link = 'Identifier' },
  ['@tag.delimiter'] = { link = 'Delimiter' },

  ['@markup.heading.1'] = { fg = '#5f8787', bold = true },
  ['@markup.heading.2'] = { fg = '#5f8787', bold = true },
  ['@markup.heading.3'] = { fg = '#5f8787', bold = true },
  ['@markup.link.label'] = { link = 'SpecialChar' },
  ['@markup.link.url'] = { link = 'Underlined' },
  ['@markup.list'] = { fg = '#5f87ff' },
  ['@markup.strong'] = { bold = true },

  -- Help
  helpHeadline = { link = 'Title' },
  helpSectionDelim = { link = 'Dimmed' },
  helpExample = { link = 'Text' },
  helpBar = { link = 'Dimmed' },
  helpHyperTextJump = { link = 'String' },
  helpHyperTextEntry = { link = 'String' },
  helpVim = { link = 'Accent' },
  helpCommand = { link = 'Text' },
  helpHeader = { link = 'Title' },
  helpNote = { link = 'Todo' },
  helpWarning = { link = 'DiagnosticWarn' },
  helpDeprecated = { link = 'DiagnosticError' },
  helpURL = { link = 'Link' },

  -- Diff
  diffAdded = { link = 'DiffAdd' },
  diffChanged = { link = 'DiffChange' },
  diffComment = { link = 'Comment' },
  diffLine = { link = 'Title' },
  diffRemoved = { link = 'DiffDelete' },
  diffSubname = { link = 'Title' },
  diffFile = { link = 'Text' },
  diffIndexLine = { link = 'Text' },
  diffNewFile = { link = 'Text' },
  diffOldFile = { link = 'Text' },

  -- gitsigns.nvim
  GitSignsAdd = { link = 'DiffAdd' },
  GitSignsChange = { link = 'DiffChange' },
  GitSignsDelete = { link = 'DiffDelete' },
  GitSignsChangedelete = { link = 'GitSignsChange' },
  GitSignsTopdelete = { link = 'GitSignsDelete' },
  GitSignsUntracked = { link = 'GitSignsAdd' },
  GitSignsCurrentLineBlame = { link = 'Ignore' },

  -- indent-blankline
  IBLIndent = { fg = c.bg_2 },
  IBLScope = { fg = c.dim_0 },
  IBLWhitespace = { link = 'Whitespace' },

  -- nvim-lspconfig
  LspInfoTitle = { link = 'Title' },
  LspInfoList = { link = 'Dimmed' },
  LspInfoFiletype = { link = 'DiagnosticOk' },
  LspInfoTip = { link = 'DiagnosticInfo' },
  LspInfoBorder = { link = 'FloatBorder' },

  -- nvim-cmp
  CmpItemAbbr = { link = 'Text' },
  CmpItemAbbrDeprecated = { link = 'Error' },
  CmpItemAbbrMatch = { link = 'Match' },
  CmpItemAbbrMatchFuzzy = { link = 'MatchFuzzy' },
  CmpItemKind = { link = 'Text' },
  CmpItemKindClass = { link = 'Type' },
  CmpItemKindColor = { link = 'StatementBuiltin' },
  CmpItemKindConstant = { link = 'ConstIdentifier' },
  CmpItemKindConstructor = { link = 'Type' },
  CmpItemKindEnum = { link = 'Type' },
  CmpItemKindEnumMember = { link = 'Property' },
  CmpItemKindEvent = { link = 'Builtin' },
  CmpItemKindField = { link = 'Property' },
  CmpItemKindFile = { link = 'Text' },
  CmpItemKindFolder = { link = 'Directory' },
  CmpItemKindFunction = { link = 'Accent' },
  CmpItemKindInterface = { link = 'Type' },
  CmpItemKindKeyword = { link = 'Keyword' },
  CmpItemKindMethod = { link = 'Accent' },
  CmpItemKindModule = { link = 'Text' },
  CmpItemKindOperator = { link = 'Operator' },
  CmpItemKindProperty = { link = 'Property' },
  CmpItemKindReference = { link = 'Accent' },
  CmpItemKindSnippet = { link = 'Text' },
  CmpItemKindStruct = { link = 'Type' },
  CmpItemKindText = { link = 'Text' },
  CmpItemKindTypeParameter = { link = 'Type' },
  CmpItemKindUnit = { link = 'Number' },
  CmpItemKindValue = { link = 'Text' },
  CmpItemKindVariable = { link = 'Identifier' },
  CmpItemMenu = { link = 'Text' },

  -- nvim-treesitter-context
  TreesitterContext = { link = 'NormalNC' },
  TreesitterContextLineNumber = { link = 'LineNr' },
  TreesitterContextSeparator = { link = 'VertSplit' },

  -- fzf-lua
  FzfLuaNormal = { bg = '#1c1c1c', fg = c.fg_0 },
  fzf1 = { bg = c.bg_2, fg = c.dim_0, bold = true },
  fzf2 = { bg = c.bg_1, fg = c.dim_0 },
  fzf3 = { bg = c.bg_0, fg = c.dim_0 },
}

for group, opts in pairs(groups) do
  hl(group, opts)
end
