set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" NERDTree
Plugin 'scrooloose/nerdtree'

" Vim-Airline - Shows current mode and other file details
Plugin 'vim-airline/vim-airline'

" Airline themes
Plugin 'vim-airline/vim-airline-themes'

" command-t - Fuzzy file search
Plugin 'wincent/command-t'

" Fugitive - Integracion de vim con git
Plugin 'tpope/vim-fugitive'

" vim-surround - quoting/parenthesizing made simple
Plugin 'tpope/vim-surround'

" vim-commentary - Comment stuff out
Plugin 'tpope/vim-commentary'

" vim-repeat - enables . repetition for some plugins
Plugin 'tpope/vim-repeat'

" vim-go - Go language support for vim
Plugin 'fatih/vim-go'

" YouCompleteMe - Code completion engine for vim
Plugin 'ycm-core/YouCompleteMe'

call vundle#end()            " required
filetype plugin indent on    " required
syntax on

""""""""""""

colorscheme badwolf
set t_Co=256

let mapleader = ","
autocmd BufWritePre * %s/\s\+$//e " Deletes trailing whitespace on save
set autoindent                    " Copies indentation from previous line
set encoding=utf-8
set wildmenu
set nobackup
set nowritebackup
set noswapfile
set ignorecase
set cursorline
set relativenumber
set number
set wildignore+=*/node_modules/*,*/target/*,*/.out,*/.git/*,*.swp
inoremap <C-C> <Esc>`^
autocmd InsertEnter * :set norelativenumber
autocmd InsertLeave * :set relativenumber

set scrolloff=3                   " Leave n lines of buffer when scrolling
set sidescrolloff=5               " Same for horizontal
set colorcolumn=100
" set background=dark

" Basic commands mapping
noremap <leader>w :w<CR>
noremap <leader>q :q!<CR>
nnoremap Y y$
setglobal pastetoggle=<F3>

" <Ctrl-l> redraws the screen and removes any search highlighting.
nnoremap <silent> <leader>L :nohl<CR><C-l>

" Copy/Paste to system clipboard
" * and + are sys clipboards
" * is PRIMARY or on select (pasted with mid mouse button)
" + is CLIPBOARD, ^C (pasted with ctrl+c)
noremap <Leader>y "+y
noremap <Leader>p "+p

" Split manipulation
noremap <silent> <leader>k :res +1<CR>
noremap <silent> <leader>j :res -1<CR>
noremap <silent> <leader>l :vertical resize +2<CR>
noremap <silent> <leader>h :vertical resize -2<CR>

" Window/buffer movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l
noremap <silent> <leader>n :bnext<CR>
noremap <leader>Q :bd<space>
noremap <leader>D :bn\|bd #<CR>
noremap <leader>e :buffer<space>

" Spaces & Tabs
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set backspace=indent,eol,start

" GUI options
if has("gui_running")
  if has("gui_win32")
    set guifont=Consolas:h11:cANSI
    set guioptions-=m
    set guioptions-=T
    set guioptions-=r
    set guioptions-=L
    au GUIEnter * sim ~x
    set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe
  endif
endif

inoremap {<CR> {<CR>}<Esc>O

" Airline settings
set laststatus=2
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline_theme = 'base16'

" Activate NERDTree
map <silent> <C-n> :NERDTreeToggle<CR>

" YouCompleteMe settings
" disables preview window on completions
" https://github.com/Valloric/YouCompleteMe#the-gycm_add_preview_to_completeopt-option
set completeopt-=preview

" command-t settings
nnoremap <leader>s :CommandT<CR>
nnoremap <leader>S :CommandTBuffer<CR>

" vim-commentary
autocmd FileType c,cpp,cs,java        setlocal commentstring=//\ %s
autocmd FileType sql                  setlocal commentstring=--\ %s
