[colors.bright]
black = "0x3d3d3d"
blue = "0x4779b3"
cyan = "0x47959e"
green = "0x53a6a6"
magenta = "0x7f62b3"
red = "0xcf4f88"
white = "0xc0c0c0"
yellow = "0xbf85cc"

[colors.cursor]
cursor = "0x8b8b8b"
text = "0xffffff"

[colors.normal]
black = "0x000000"
blue = "0x395573"
cyan = "0x2b7694"
green = "0x287373"
magenta = "0x5e468c"
red = "0x8a2f58"
white = "0x899ca1"
yellow = "0x914e89"

[colors.primary]
background = "0x1c1c1c"
# bright_background = "0x3a3a3a"
bright_foreground = "0xd9d9d9"
# dim_background = "0x202020"
dim_foreground = "0xdbdbdb"
foreground = "0xd6d6d6"
