set -g prefix C-f
unbind C-b

bind r source-file ~/.tmux.conf \; display "Reloaded!"
set -sg escape-time 0
set -g focus-events on
set -g base-index 1

# set -g default-terminal "tmux-256color" try
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g window-style 'fg=color255, bg=color235'
set -g window-active-style 'fg=color255,bg=color234'  #black=color0
set -g status-bg color234 #color0
set -g status-fg color255
set-window-option -g window-status-style fg=color255
set-window-option -g window-status-current-style "fg=color0 bg=color141"
set -g status-right "#(/bin/bash ~/dotfiles/tmux/scripts/kube-ctx.sh)"
set -g status-right-length 100 # Prevents k8s info from being cut out
set-window-option -g window-status-format "#I:#W#(printf '%%s\n' '#F' | tr 'Z' '')"
set-window-option -g window-status-current-format "#I:#W#(printf '%%s\n' '#F' | tr 'Z' '')"

set-window-option -g mode-keys vi
bind -T copy-mode-vi 'v' send-keys -X begin-selection

bind c new-window -c "$HOME"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind -n 'C-\' run-shell -b ~/dotfiles/tmux/scripts/tmux-toggle-term.sh

bind p run-shell "tmux popup -E ~/dotfiles/tmux/scripts/dir-jump.sh"
bind w run-shell "tmux popup -E ~/dotfiles/tmux/scripts/window-jump.sh"
bind s run-shell "tmux popup -E ~/dotfiles/tmux/scripts/session-jump.sh"
bind t command-prompt "kill-window -t '%%'"
bind x kill-window
bind f last-window

bind m switch-client -T layout-menu
bind -T layout-menu 1 set-window-option main-pane-width 60% \; select-layout main-vertical
bind -T layout-menu 2 set-window-option main-pane-height 50% \; select-layout main-horizontal
bind -T layout-menu 3 select-layout tiled

bind S \
    if-shell "tmux show-window-options -v monitor-silence | grep -q 5" \
        "setw monitor-silence 0; display-message 'Silence Monitoring: OFF'" \
        "setw monitor-silence 5; display-message 'Silence Monitoring: ON (5s)'"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

bind - switch-client -T above9
bind -T above9 0 select-window -t:10
bind -T above9 1 select-window -t:11
bind -T above9 2 select-window -t:12
bind -T above9 3 select-window -t:13
bind -T above9 4 select-window -t:14
bind -T above9 5 select-window -t:15
bind -T above9 6 select-window -t:16
bind -T above9 7 select-window -t:17
bind -T above9 8 select-window -t:18
bind -T above9 9 select-window -t:19

if-shell "uname -s | grep -q Darwin" "source ~/dotfiles/tmux/macos.conf"
