export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="sop"
CASE_SENSITIVE="true"

plugins=(
  zsh-autosuggestions # https://github.com/zsh-users/zsh-autosuggestions
  zsh-syntax-highlighting # https://github.com/zsh-users/zsh-syntax-highlighting
)

export XDG_CONFIG_HOME="$HOME/.config"

source $ZSH/oh-my-zsh.sh
source $HOME/.aliases

function mkcd { command mkdir -p $1 && cd $1 }
function jqp { jq -R -r '. as $line | try fromjson catch $line' }
function lenv { set -a; source .env; set +a }

if [[ $OSTYPE == 'darwin'* ]]; then
  export GOROOT="$(brew --prefix golang)/libexec"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  export GOROOT=/usr/local/go
fi

export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:$HOME/.cargo/bin

export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# Helm
if command -v helm &> /dev/null
then
  source <(helm completion zsh)
fi

# Launches ssh-agent
if command -v keychain &> /dev/null
then
  eval `keychain --eval --agents ssh $HOME/.ssh/id_dot`
fi

# set key repeat rate. delay 400 milisecond, 50 per sec
if command -v xset &> /dev/null
then
  xset r rate 400 50
fi

if command -v kubectl &> /dev/null
then
  source <(kubectl completion zsh)
  export KUBE_EDITOR="nvim"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -d /opt/podman ] && export PATH="/opt/podman/bin:$PATH"
