export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="sop"
CASE_SENSITIVE="true"

plugins=(
  zsh-autosuggestions
)

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
export XDG_CONFIG_HOME="$HOME/.config"

source $ZSH/oh-my-zsh.sh
source $HOME/.aliases

function mkcd { command mkdir $1 && cd $1 }
function jqp { jq -R -r '. as $line | try fromjson catch $line' }

if [[ $OSTYPE == 'darwin'* ]]; then
  export JAVA_HOME=$(/usr/libexec/java_home)
  export GOROOT="$(brew --prefix golang)/libexec"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  export GOROOT=/usr/local/go
fi

export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

export PATH="$HOME/.cargo/bin:$PATH"

# Helm
if command -v helm &> /dev/null
then
  source <(helm completion zsh)
fi

# Bat
export BAT_THEME="ansi"

# Launches ssh-agent
if command -v keychain &> /dev/null
then
  eval `keychain --eval --agents ssh $HOME/.ssh/id_dot`
fi

# set key repeat rate. delay 400 milisecond, 50 per sec
if command -v xset &> /dev/null
then
  xset r rate 400 50
fi

if command -v kubectl &> /dev/null
then
  source <(kubectl completion zsh)
  export KUBE_EDITOR="/usr/local/bin/nvim"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
